//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int AgreementID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string AgreementAmount { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string DocURL { get; set; }
        public string HTMLURL { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadBy { get; set; }
        public string UploadURL { get; set; }
        public string AllotmentLetter { get; set; }
        public string AllotmentLetterBy { get; set; }
        public Nullable<System.DateTime> AllotmentLetterDate { get; set; }
        public string WelComeLetter { get; set; }
        public string AssuredDocURL { get; set; }
        public string AssuredHTMLURL { get; set; }
    }
}
