//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssuredReturn
    {
        public int AssuredReturnID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public string FlatName { get; set; }
        public string MonthName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> TDS { get; set; }
    }
}
