//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerPayment
    {
        public int BrokerPaymentID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string PaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
