//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerToProperty
    {
        public int BrokerToPropertyID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> BrokerID { get; set; }
        public Nullable<decimal> BrokerAmount { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<int> ApproveStatus { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
