//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CityCode { get; set; }
        public string StateCode { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> AreaID { get; set; }
    }
}
