//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public string AppTitle { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Title { get; set; }
        public string PName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PAN { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CoAppTitle { get; set; }
        public string CoFName { get; set; }
        public string CoMName { get; set; }
        public string CoLName { get; set; }
        public string CoAddress1 { get; set; }
        public string CoAddress2 { get; set; }
        public string CoCity { get; set; }
        public string CoState { get; set; }
        public string CoCountry { get; set; }
        public string CoPAN { get; set; }
        public string CoMobileNo { get; set; }
        public string Address1Out { get; set; }
        public string Address2Out { get; set; }
        public string CityOut { get; set; }
        public string StateOut { get; set; }
        public string CountryOut { get; set; }
        public string PANOut { get; set; }
        public string MobileOut { get; set; }
        public string AlternateMobile { get; set; }
        public string LandLine { get; set; }
        public string EmailID { get; set; }
        public string AlternateEmail { get; set; }
        public string Website { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public string LienField { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankAddress { get; set; }
        public string BankBranch { get; set; }
        public Nullable<bool> IsPAN { get; set; }
        public Nullable<bool> IsPhoto { get; set; }
        public Nullable<bool> IsAddressPf { get; set; }
        public Nullable<bool> IsRationCard { get; set; }
        public Nullable<bool> IsDrivingLicence { get; set; }
        public Nullable<bool> IsPassport { get; set; }
        public Nullable<bool> IsVoterCard { get; set; }
        public Nullable<int> IsTransfer { get; set; }
        public string Status { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string SecCoAppTitle { get; set; }
        public string SecCoFName { get; set; }
        public string SecCoMName { get; set; }
        public string SecCoLName { get; set; }
        public string SecCoAddress1 { get; set; }
        public string SecCoAddress2 { get; set; }
        public string SecCoCity { get; set; }
        public string SecCoState { get; set; }
        public string SecCoCountry { get; set; }
        public string SecCoMobileNo { get; set; }
        public string SecCoPAN { get; set; }
        public string CoTitle { get; set; }
        public string CoPName { get; set; }
        public string SecCoTitle { get; set; }
        public string SecCoPName { get; set; }
        public Nullable<int> IsConstruction { get; set; }
        public string PhotoImagePath { get; set; }
        public string AddPfImagePath { get; set; }
        public string DVImagePath { get; set; }
        public string VoterCardImagePath { get; set; }
        public string PassportImagePath { get; set; }
        public string RationCardImagePath { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CoDOB { get; set; }
        public Nullable<System.DateTime> SecCoDOB { get; set; }
        public string PANImagePath { get; set; }
        public Nullable<bool> CoIsPAN { get; set; }
        public Nullable<bool> CoIsPhoto { get; set; }
        public Nullable<bool> CoIsAddressPf { get; set; }
        public Nullable<bool> CoIsRationCard { get; set; }
        public Nullable<bool> CoIsDrivingLicence { get; set; }
        public Nullable<bool> CoIsVoterCard { get; set; }
        public Nullable<bool> CoIsPassport { get; set; }
        public Nullable<bool> SecCoIsPAN { get; set; }
        public Nullable<bool> SecCoIsPhoto { get; set; }
        public Nullable<bool> SecCoIsAddressPf { get; set; }
        public Nullable<bool> SecCoIsRationCard { get; set; }
        public Nullable<bool> SecCoIsDrivingLicence { get; set; }
        public Nullable<bool> SecCoIsVoterCard { get; set; }
        public Nullable<bool> SecCoIsPassport { get; set; }
        public string CoPhotoImagePath { get; set; }
        public string CoAddPfImagePath { get; set; }
        public string CoDVImagePath { get; set; }
        public string CoVoterCardImagePath { get; set; }
        public string CoPassportImagePath { get; set; }
        public string CoRationCardImagePath { get; set; }
        public string CoPANImagePath { get; set; }
        public string SecCoPhotoImagePath { get; set; }
        public string SecCoAddPfImagePath { get; set; }
        public string SecCoDVImagePath { get; set; }
        public string SecCoVoterCardImagePath { get; set; }
        public string SecCoPassportImagePath { get; set; }
        public string SecCoRationCardImagePath { get; set; }
        public string SecCoPANImagePath { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public string PinCode { get; set; }
        public string ExecutiveName { get; set; }
        public string CoPinCode { get; set; }
        public string SecCoPinCode { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Distt { get; set; }
        public string LegalOptionDate { get; set; }
        public Nullable<int> panallowstatus { get; set; }
        public string affidavit { get; set; }
        public Nullable<bool> SaleStatus { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string UserName { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
    }
}
