//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatTypeSize
    {
        public FlatTypeSize()
        {
            this.PlanTypeMasters = new HashSet<PlanTypeMaster>();
        }
    
        public int FlatTypeSizeID { get; set; }
        public Nullable<int> FlatTypeID { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
    
        public virtual FlatType FlatType { get; set; }
        public virtual ICollection<PlanTypeMaster> PlanTypeMasters { get; set; }
    }
}
