//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public Flat()
        {
            this.FlatCharges = new HashSet<FlatCharge>();
            this.FlatInstallmentDetails = new HashSet<FlatInstallmentDetail>();
            this.FlatOCharges = new HashSet<FlatOCharge>();
            this.FlatPLCs = new HashSet<FlatPLC>();
            this.SaleFlats = new HashSet<SaleFlat>();
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.ReminderLetters = new HashSet<ReminderLetter>();
        }
    
        public int FlatID { get; set; }
        public int FloorID { get; set; }
        public string FlatType { get; set; }
        public string FlatName { get; set; }
        public string FlatNo { get; set; }
        public Nullable<decimal> FlatSize { get; set; }
        public string FlatSizeUnit { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> BadRooms { get; set; }
        public Nullable<bool> IsFurnished { get; set; }
        public Nullable<bool> LivingRoom { get; set; }
        public Nullable<bool> ServantRoom { get; set; }
        public Nullable<bool> Kitchen { get; set; }
        public Nullable<bool> Balconies { get; set; }
        public Nullable<bool> BathRooms { get; set; }
        public Nullable<bool> PoojaRoom { get; set; }
        public Nullable<bool> StudyRoom { get; set; }
        public Nullable<bool> AC { get; set; }
        public Nullable<bool> Intercom { get; set; }
        public Nullable<bool> Cupboards { get; set; }
        public Nullable<bool> WashingArea { get; set; }
        public Nullable<bool> PowerBackup { get; set; }
        public Nullable<bool> GASLine { get; set; }
        public Nullable<bool> HomeAutomation { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
        public Nullable<int> FlatOrder { get; set; }
        public string Status { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual ICollection<FlatCharge> FlatCharges { get; set; }
        public virtual ICollection<FlatInstallmentDetail> FlatInstallmentDetails { get; set; }
        public virtual ICollection<FlatOCharge> FlatOCharges { get; set; }
        public virtual ICollection<FlatPLC> FlatPLCs { get; set; }
        public virtual ICollection<SaleFlat> SaleFlats { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<ReminderLetter> ReminderLetters { get; set; }
    }
}
