//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlatType
    {
        public FlatType()
        {
            this.FlatTypeSizes = new HashSet<FlatTypeSize>();
        }
    
        public int FlatTypeID { get; set; }
        public string FType { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<bool> IsFurnished { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
    
        public virtual ICollection<FlatTypeSize> FlatTypeSizes { get; set; }
    }
}
