//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public Floor()
        {
            this.Flats = new HashSet<Flat>();
        }
    
        public int FloorID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public Nullable<int> FloorNo { get; set; }
        public string FloorName { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
    
        public virtual ICollection<Flat> Flats { get; set; }
        public virtual Tower Tower { get; set; }
    }
}
