//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatePayment
    {
        public int LatePaymentID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string InstallmentNo { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> ReceiveAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
    }
}
