//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRecord
    {
        public int PaymentRecordID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public int SaleID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Action { get; set; }
        public string PayType { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
    }
}
