//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCancel
    {
        public int PaymentCancelID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> UnCancelDate { get; set; }
        public string Remarks { get; set; }
        public string UnCancelRemark { get; set; }
        public string CancelBy { get; set; }
        public string UnCancelBy { get; set; }
        public string Status { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
    }
}
