//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDiscount
    {
        public PaymentDiscount()
        {
            this.PaymentDiscountApprovals = new HashSet<PaymentDiscountApproval>();
        }
    
        public int PaymentDiscountID { get; set; }
        public int SaleID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
        public virtual ICollection<PaymentDiscountApproval> PaymentDiscountApprovals { get; set; }
    }
}
