//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTransferFee
    {
        public int PayTransferID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string PaymentNo { get; set; }
        public string AmtRcvdinWords { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> BankCharges { get; set; }
        public Nullable<System.DateTime> BankClearanceDate { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Activity { get; set; }
        public string Remarks { get; set; }
    }
}
