//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanInstallment
    {
        public PlanInstallment()
        {
            this.FlatInstallmentDetails = new HashSet<FlatInstallmentDetail>();
        }
    
        public int PlanInstallmentID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string Installment { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
        public Nullable<int> IntervalDays { get; set; }
    
        public virtual ICollection<FlatInstallmentDetail> FlatInstallmentDetails { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
