//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanTypeMaster
    {
        public int PlanTypeMasterID { get; set; }
        public Nullable<int> FlatTypeSizeID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string PlanName { get; set; }
        public Nullable<decimal> AmountSqFt { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
    
        public virtual FlatTypeSize FlatTypeSize { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
