//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.PlanInstallments = new HashSet<PlanInstallment>();
            this.PlanTypeMasters = new HashSet<PlanTypeMaster>();
        }
    
        public int PlanID { get; set; }
        public string PlanName { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<PlanInstallment> PlanInstallments { get; set; }
        public virtual ICollection<PlanTypeMaster> PlanTypeMasters { get; set; }
    }
}
