//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectTypes = new HashSet<ProjectType>();
            this.Towers = new HashSet<Tower>();
            this.UserProperties = new HashSet<UserProperty>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
        public string PName { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string ReceiptPrefix { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string OfficeAddress { get; set; }
        public string District { get; set; }
        public string Village { get; set; }
        public string Tehsil { get; set; }
        public string Jurisdiction { get; set; }
        public Nullable<System.DateTime> PossessionDate { get; set; }
        public string ReceiptNo { get; set; }
        public string AuthoritySign { get; set; }
    
        public virtual ICollection<ProjectType> ProjectTypes { get; set; }
        public virtual ICollection<Tower> Towers { get; set; }
        public virtual ICollection<UserProperty> UserProperties { get; set; }
    }
}
