//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderLetter
    {
        public int ReminderLetterID { get; set; }
        public string LetterType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
    
        public virtual SaleFlat SaleFlat { get; set; }
    }
}
