//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleFlat
    {
        public SaleFlat()
        {
            this.Customers = new HashSet<Customer>();
            this.LatePayments = new HashSet<LatePayment>();
            this.Payments = new HashSet<Payment>();
            this.PaymentCancels = new HashSet<PaymentCancel>();
            this.PaymentOthers = new HashSet<PaymentOther>();
            this.PaymentOtherCancels = new HashSet<PaymentOtherCancel>();
            this.PaymentRecords = new HashSet<PaymentRecord>();
            this.PaymentRefunds = new HashSet<PaymentRefund>();
            this.PayServiceTaxes = new HashSet<PayServiceTax>();
            this.PropertyRemarks = new HashSet<PropertyRemark>();
            this.PropertyTransfers = new HashSet<PropertyTransfer>();
            this.RefundProperties = new HashSet<RefundProperty>();
            this.UploadAgreements = new HashSet<UploadAgreement>();
            this.PaymentDiscounts = new HashSet<PaymentDiscount>();
            this.ReminderLetters = new HashSet<ReminderLetter>();
        }
    
        public int SaleID { get; set; }
        public Nullable<int> FlatID { get; set; }
        public string Aggrement { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TotalAmtInWords { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DemandStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string CreatedBy { get; set; }
        public string PlanName { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Flat Flat { get; set; }
        public virtual ICollection<LatePayment> LatePayments { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<PaymentCancel> PaymentCancels { get; set; }
        public virtual ICollection<PaymentOther> PaymentOthers { get; set; }
        public virtual ICollection<PaymentOtherCancel> PaymentOtherCancels { get; set; }
        public virtual ICollection<PaymentRecord> PaymentRecords { get; set; }
        public virtual ICollection<PaymentRefund> PaymentRefunds { get; set; }
        public virtual ICollection<PayServiceTax> PayServiceTaxes { get; set; }
        public virtual ICollection<PropertyRemark> PropertyRemarks { get; set; }
        public virtual ICollection<PropertyTransfer> PropertyTransfers { get; set; }
        public virtual ICollection<RefundProperty> RefundProperties { get; set; }
        public virtual ICollection<UploadAgreement> UploadAgreements { get; set; }
        public virtual ICollection<PaymentDiscount> PaymentDiscounts { get; set; }
        public virtual ICollection<ReminderLetter> ReminderLetters { get; set; }
    }
}
