//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public int TaxMasterID { get; set; }
        public string TaxName { get; set; }
        public string TaxTag { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<System.DateTime> ApplyTill { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
