//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tower
    {
        public Tower()
        {
            this.Floors = new HashSet<Floor>();
        }
    
        public int TowerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
        public string TowerName { get; set; }
        public string TowerNo { get; set; }
        public string Block { get; set; }
        public Nullable<bool> Security { get; set; }
        public Nullable<bool> PlayArea { get; set; }
        public Nullable<bool> PowerBackup { get; set; }
        public Nullable<bool> SwimmingPool { get; set; }
        public Nullable<bool> Gym { get; set; }
        public Nullable<bool> Garden { get; set; }
        public Nullable<bool> Library { get; set; }
        public Nullable<bool> CommunityHall { get; set; }
        public Nullable<bool> ClubHourse { get; set; }
        public Nullable<bool> JoggingTrack { get; set; }
        public Nullable<bool> Lift { get; set; }
        public Nullable<bool> Internet { get; set; }
        public Nullable<bool> InternalRoad { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrBy { get; set; }
    
        public virtual ICollection<Floor> Floors { get; set; }
        public virtual Project Project { get; set; }
    }
}
