//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProperty
    {
        public int UserPropertyID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string AssignUser { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
